### PR TITLE
Windows tests

### PR DESCRIPTION
**Pull request by seangenabe**
Windows test. (#9)

I've written a small test which includes invoking the command interpreter (cmd.exe) to check if it receives and sends the arguments properly, as well a simple string test.

I'm not sure if you'd like how I replaced your test runner though, which I assume is written in bash. The test runner script I made should mimic what it does.

I also put a condition in your tests so they won't run on Windows.

### CODE REVIEW

**Comment by binki** [comment]
These tests fail for me on Windows:

```
C:\Users\ohnob\repos\node-shell-escape>npm install-test

> shell-escape@0.2.1 test C:\Users\ohnob\repos\node-shell-escape
> for f in test/*; do echo "$f"; node "$f" || exit 1; echo; done; echo Passed; exit 0

f was unexpected at this time.
npm ERR! Test failed.  See above for more details.
```

but it just looks like a rigging issue.

**Comment by binki** [comment]
Oh, I’m stupid, I forgot to switch branches first.  Runs fine on Windows and also on Linux.

May these changes be released to the npm module? That’d make my life a lot easier because I need these changes to use `shell-escape` on Windows.

**Comment by binki** [comment]
(I’ve since decided to just use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn))

**Comment by xxorax** [comment]
Here is the same problem in mentionned in [my comment](https://github.com/xxorax/node-shell-escape/pull/10#issuecomment-360963990) on #10.

Running these tests on your local machine does not means they will pass on a remote server.

**Pull request closed without merging**
