### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by seangenabe**
Enables Windows support (#9)

### CODE REVIEW

**Comment by andersk** [comment]
The corresponding [code in cross-spawn](https://github.com/IndigoUnited/node-cross-spawn/blob/5.1.0/lib/util/escapeArgument.js) looks a lot simpler.

**Comment by binki** [comment]
Because escaping arguments is not the only issue with launching processes portably on different platforms, I recommend to just use cross-spawn and its `spawn()` (which accepts an array of arguments) instead of this package.

**Comment by andersk** [comment]
@binki Absolutely—but in more complicated use cases like passing a command to a command, additional layers of manual shell quoting may still be required.

Some of these complicated use cases, like running a command over SSH on a Unix server from a Windows client, may even require shell quoting for a platform other than the current one. So I would suggest providing three functions, one for Windows, one for Unix, and one that switches on the current platform.

**Comment by xxorax** [comment]
Sorry for late reply. This lib is not intended to support Windows shell like this.

This pull request escape shell args based on the [current system](https://github.com/xxorax/node-shell-escape/pull/10/files#diff-32b62cc9396a2d7dc59e3b950a7bc8d6R7), which is maybe not what we want (how about escaping to execute a command on an other system ? ex: by ssh).

So it should set the shell type with some option. That means redefining the API.

I'm open to it, maybe sub-functions to escape string by shell (like shellescape.sh(), shellescape.bash(). shellescape.powershell(), ..etc).

Also note that the [code in cross-spawn](https://github.com/IndigoUnited/node-cross-spawn/blob/5.1.0/lib/util/escapeArgument.js) mentionned in the comment below does not escape anything inside the double-quotes except quotes (and so it will not pass the current tests of node-shell-escape).

**Comment by andersk** [comment]
> Also note that the [code in cross-spawn](https://github.com/IndigoUnited/node-cross-spawn/blob/5.1.0/lib/util/escapeArgument.js) mentionned in the comment below does not escape anything inside the double-quotes except quotes (and so it will not pass the current tests of node-shell-escape).

To be clear, it also escapes any backslashes inside double-quotes that belong to a sequence of backslashes preceding an escaped double-quote or the end of the string. (This is wrong for Unix, but is the only right thing for Windows, where doubled backslashes are only undoubled within such sequences.)

**Pull request closed without merging**
